### ISSUE TITLE
Bitcoin wallet address and transaction import

### ISSUE THREAD

**Issue by lkthomas** [foxfolio/foxfolio-desktop#11]
is it possible to import Bitcoin wallet address and all the transaction so that I could keep everything in sync?

**Comment by greimela** [comment]
That is currently not implemented, no.

But it would be rather straightforward to add.
I'll look into it.

**Comment by lkthomas** [comment]
version 0.0.9 seems still don't have the code needed to pull from bitcoin wallet address.

**Comment by greimela** [comment]
That's true, that feature will take a bit more time.
