### ISSUE TITLE
large number problem

### ISSUE THREAD

**Issue by lkthomas** [foxfolio/foxfolio-desktop#12]
![image](https://user-images.githubusercontent.com/581053/57441450-930b1900-727c-11e9-818c-8b793954a986.png)

Can you please check why the USD number is incorrect?

**Comment by greimela** [comment]
That's just the way how the app currently presents large numbers.
For example 100,000 is represented as 1e+5, meaning a 1 with 5 zeros appended.

But I can fix this in the next version and always show the full number.

**Comment by greimela** [comment]
This has been released in [v0.0.10](https://github.com/foxfolio/foxfolio-desktop/releases/tag/v0.0.10).
