### ISSUE TITLE
packaging

### ISSUE THREAD

**Issue by Projects-Hub** [foxfolio/foxfolio-desktop#15]
How do I package it?

**Comment by greimela** [comment]
You can simply run `yarn run package` to build the package for your OS.

**Comment by Projects-Hub** [comment]
I did, but got an error:
![Uploading 20191119_084231.jpg…]()
![Uploading 20191119_084222.jpg…]()

**Comment by Projects-Hub** [comment]
It said fortfolio@0.0.11 build 'concurrently "npm run build-main" " npm run build-renderer"' Exit status 1
