### ISSUE TITLE
Price not shown

### ISSUE THREAD

**Issue by mschrimpf** [foxfolio/foxfolio-desktop#6]
For kucoin.com, the prize of one coin is not shown in the portfolio. AFAIK, it worked when these were bitcoin.
![act_kucoin-no_values](https://user-images.githubusercontent.com/5308236/35397641-fe5bb538-01bd-11e8-9cf7-49bf423f7ae2.PNG)

**Comment by greimela** [comment]
Yes, that is the state of a portfolio row if there is no price available.
Foxfolio retrieves the prices using the Cryptocompare API, but they do not provide prices for all coins. 

I plan to retrieve the price directly from the exchange if it is not available on Cryptocompare.

**Comment by mschrimpf** [comment]
Perhaps slightly off-topic, but wouldn't it make sense to always retrieve the prize from the exchange where the coin is located?

**Comment by greimela** [comment]
Only if you have all coins of one kind at the same exchange.

As soon as they are spreaded over multiple exchanges or wallets it gets difficult to determine which price to use. I'd say in this case the aggregated price from Cryptocompare makes sense.

**Comment by greimela** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Keine Preise für manche Coins](https://trello.com/c/bnDIHa2E/50-keine-preise-f%C3%BCr-manche-coins)

**Comment by greimela** [comment]
This issue originates in the coinlist provided by Cryptocompare.
It contains two symbols `ACT` and `ACT*` but only provides price data for the latter.

The new release [0.0.5](https://github.com/foxfolio/foxfolio-desktop/releases/tag/v0.0.5) unifies token symbols to prevent this.

Does it fix your problem?

**Comment by mschrimpf** [comment]
Yup! Thanks
